default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portal_webaula_development

production:
  <<: *default
  database: portal_webaula_production
  username: lucas
  password: <%= ENV['ECOMMERCE_API_DATABASE_PASSWORD'] %>